name: Go Build and Release (Master Branch)

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-linux:
    name: Build Linux Binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24'

      - name: Get current timestamp
        id: timestamp
        run: echo "::set-output name=now::$(date +'%Y%m%d%H%M%S')"

      - name: Build Linux Binary
        env:
          VERSION: ${{ steps.timestamp.outputs.now }}
        run: |
          go build -ldflags "-X main.Version=${VERSION}" -o eget
      
      - name: Upload Binary to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: eget
          tag: ${{ steps.timestamp.outputs.now }}
          overwrite: true
          file_glob: false
          release_name: "Release ${{ steps.timestamp.outputs.now }}"
